"""Tests for gzkit.rules — instruction classification and nested AGENTS.md."""

import tempfile
import unittest
from pathlib import Path

from gzkit.rules import (
    _GENERATED_MARKER,
    classify_instruction_rules,
    sync_claude_rules,
    sync_nested_agents_md,
    validate_rule_placement,
)


def _instruction_file(apply_to: str, body: str, *, audience: str | None = None) -> str:
    """Build a minimal .instructions.md file."""
    lines = ["---", f'applyTo: "{apply_to}"']
    if audience is not None:
        lines.append(f"audience: {audience}")
    lines.append("---")
    lines.append("")
    lines.append(body)
    return "\n".join(lines)


class TestClassifyInstructionRules(unittest.TestCase):
    """Test classify_instruction_rules()."""

    def test_shared_default_when_audience_absent(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            inst = root / ".github" / "instructions"
            inst.mkdir(parents=True)
            (inst / "tests.instructions.md").write_text(
                _instruction_file("tests/**", "# Test rules")
            )

            rules = classify_instruction_rules(root)

            self.assertEqual(len(rules), 1)
            self.assertEqual(rules[0].audience, "shared")
            self.assertFalse(rules[0].is_global)
            self.assertEqual(rules[0].subtree_prefixes, ["tests"])

    def test_claude_only_explicit(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            inst = root / ".github" / "instructions"
            inst.mkdir(parents=True)
            (inst / "secret.instructions.md").write_text(
                _instruction_file("src/**", "# Claude secret", audience="claude-only")
            )

            rules = classify_instruction_rules(root)

            self.assertEqual(len(rules), 1)
            self.assertEqual(rules[0].audience, "claude-only")

    def test_global_scope_detected(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            inst = root / ".github" / "instructions"
            inst.mkdir(parents=True)
            (inst / "global.instructions.md").write_text(_instruction_file("**/*", "# Global rule"))

            rules = classify_instruction_rules(root)

            self.assertEqual(len(rules), 1)
            self.assertTrue(rules[0].is_global)
            self.assertEqual(rules[0].subtree_prefixes, [])

    def test_multi_pattern_extracts_multiple_prefixes(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            inst = root / ".github" / "instructions"
            inst.mkdir(parents=True)
            (inst / "multi.instructions.md").write_text(
                _instruction_file("src/cli/**,tests/**", "# Multi")
            )

            rules = classify_instruction_rules(root)

            self.assertEqual(len(rules), 1)
            self.assertIn("src/cli", rules[0].subtree_prefixes)
            self.assertIn("tests", rules[0].subtree_prefixes)


class TestSyncNestedAgentsMd(unittest.TestCase):
    """Test sync_nested_agents_md()."""

    def test_generates_nested_file_for_subtree_scope(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            inst = root / ".github" / "instructions"
            inst.mkdir(parents=True)
            (inst / "tests.instructions.md").write_text(
                _instruction_file("tests/**", "# Test Policy\n\nUse unittest.")
            )
            (root / "tests").mkdir()

            updated = sync_nested_agents_md(root)

            self.assertEqual(len(updated), 1)
            agents = root / "tests" / "AGENTS.md"
            self.assertTrue(agents.exists())
            content = agents.read_text()
            self.assertIn("Generated by gzkit", content)
            self.assertIn("# tests Agent Instructions", content)
            self.assertIn("# Test Policy", content)
            self.assertIn("Use unittest.", content)

    def test_skips_nonexistent_subtree_dirs(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            inst = root / ".github" / "instructions"
            inst.mkdir(parents=True)
            (inst / "warehouse.instructions.md").write_text(
                _instruction_file("src/airlineops/warehouse/**", "# Warehouse")
            )
            # Do NOT create the subtree directory

            updated = sync_nested_agents_md(root)

            self.assertEqual(updated, [])

    def test_deletes_stale_nested_agents_md(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            inst = root / ".github" / "instructions"
            inst.mkdir(parents=True)

            # Create a stale nested AGENTS.md with the generated marker
            stale_dir = root / "old_subtree"
            stale_dir.mkdir()
            stale_file = stale_dir / "AGENTS.md"
            stale_file.write_text(f"{_GENERATED_MARKER}\n# Stale content\n", encoding="utf-8")

            # No instruction files reference old_subtree
            (inst / "tests.instructions.md").write_text(
                _instruction_file("tests/**", "# Test rules")
            )
            (root / "tests").mkdir()

            sync_nested_agents_md(root)

            self.assertFalse(stale_file.exists())

    def test_preserves_non_generated_agents_md(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            inst = root / ".github" / "instructions"
            inst.mkdir(parents=True)

            # Manually created AGENTS.md (no generated marker)
            manual_dir = root / "manual"
            manual_dir.mkdir()
            manual_file = manual_dir / "AGENTS.md"
            manual_file.write_text("# Hand-written agent rules\n")

            (inst / "tests.instructions.md").write_text(
                _instruction_file("tests/**", "# Test rules")
            )
            (root / "tests").mkdir()

            sync_nested_agents_md(root)

            self.assertTrue(manual_file.exists())
            self.assertIn("Hand-written", manual_file.read_text())

    def test_global_scope_shared_rules_no_nested_file(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            inst = root / ".github" / "instructions"
            inst.mkdir(parents=True)
            (inst / "global.instructions.md").write_text(
                _instruction_file("**/*", "# Global governance")
            )

            updated = sync_nested_agents_md(root)

            self.assertEqual(updated, [])


class TestSyncClaudeRulesFromRules(unittest.TestCase):
    """Test that sync_claude_rules (now in rules.py) still works."""

    def test_claude_only_rules_still_mirror(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            inst = root / ".github" / "instructions"
            inst.mkdir(parents=True)
            (inst / "secret.instructions.md").write_text(
                _instruction_file("src/**", "# Secret Claude rule", audience="claude-only")
            )

            updated = sync_claude_rules(root)

            self.assertEqual(len(updated), 1)
            target = root / ".claude" / "rules" / "secret.md"
            self.assertTrue(target.exists())
            self.assertIn("Secret Claude rule", target.read_text())

    def test_uses_config_claude_rules_path(self) -> None:
        from gzkit.config import GzkitConfig, PathConfig

        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            inst = root / ".github" / "instructions"
            inst.mkdir(parents=True)
            (inst / "demo.instructions.md").write_text(_instruction_file("tests/**", "# Demo rule"))

            config = GzkitConfig(paths=PathConfig(claude_rules=".custom/rules"))
            updated = sync_claude_rules(root, config)

            self.assertEqual(len(updated), 1)
            target = root / ".custom" / "rules" / "demo.md"
            self.assertTrue(target.exists())


class TestValidateRulePlacement(unittest.TestCase):
    """Test validate_rule_placement()."""

    def test_catches_missing_nested_agents_md(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            inst = root / ".github" / "instructions"
            inst.mkdir(parents=True)
            (inst / "tests.instructions.md").write_text(
                _instruction_file("tests/**", "# Test rules")
            )
            (root / "tests").mkdir()
            # Do NOT create nested AGENTS.md

            warnings = validate_rule_placement(root)

            self.assertTrue(len(warnings) > 0)
            self.assertIn("tests", warnings[0])
            self.assertIn("no nested AGENTS.md", warnings[0])

    def test_no_warnings_when_nested_agents_exists(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            inst = root / ".github" / "instructions"
            inst.mkdir(parents=True)
            (inst / "tests.instructions.md").write_text(
                _instruction_file("tests/**", "# Test rules")
            )
            tests_dir = root / "tests"
            tests_dir.mkdir()
            (tests_dir / "AGENTS.md").write_text(f"{_GENERATED_MARKER}\n# Tests\n")

            warnings = validate_rule_placement(root)

            self.assertEqual(warnings, [])

    def test_catches_claude_only_not_mirrored(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            inst = root / ".github" / "instructions"
            inst.mkdir(parents=True)
            (inst / "secret.instructions.md").write_text(
                _instruction_file("src/**", "# Secret", audience="claude-only")
            )
            # No .claude/rules/secret.md exists

            warnings = validate_rule_placement(root)

            self.assertTrue(len(warnings) > 0)
            self.assertIn("claude-only", warnings[0])
