"""Rule classification and native path-scoped instruction surfaces.

Extracts instruction rule sync from sync.py and adds:
- audience-based classification (shared vs claude-only)
- nested AGENTS.md generation for shared subtree rules
- rule placement validation
- canonical rule loading and validation from .gzkit/rules/

@covers ADR-0.16.0  OBPI-0.16.0-02 rules-as-content
"""

import logging
from pathlib import Path
from typing import Any, Literal

import yaml
from pydantic import BaseModel, ConfigDict, Field

from gzkit.config import GzkitConfig
from gzkit.surface_write import dir_exists, ensure_dir, remove_if_present, write_text_if_changed

_logger = logging.getLogger(__name__)

_GENERATED_MARKER = "<!-- Generated by gzkit — do not edit manually -->"

#: Generated per-subtree surfaces, which are NOT rule files even when they sit in
#: the canonical rules directory. Three scanners each skipped ``AGENTS.md`` by
#: literal name -- ``load_rules``, ``validators.rule_version_markers`` and
#: ``validators.unscoped_rules``. Each literal was a one-member allowlist for a
#: family, so adding the Claude redirect beside it (GHI #923) made
#: `.gzkit/rules/CLAUDE.md` a rule file to all three at once: a missing
#: frontmatter delimiter, a missing rule-version marker, and a missing `paths:`
#: scope. Public and shared so a fourth generated surface cannot reopen this
#: three ways.
NESTED_SURFACE_NAMES: frozenset[str] = frozenset({"AGENTS.md", "CLAUDE.md"})


def _classify_rule_file(
    path: Path,
    *,
    project_root: Path | None = None,
) -> Literal["canonical", "package_only", "runtime_state"]:
    """Classify a rules-surface file into one of three content classes.

    canonical: *.md rule files, plus any non-Python/non-markdown asset that has
               a counterpart at ``.gzkit/rules/<rel>`` (e.g. JSON sidecars
               authored on the canonical side).
    package_only: ``__init__.py``, ``__pycache__/**``, Python modules with no
                  ``.gzkit/rules/`` counterpart (e.g. ``_scaffolder.py``), and
                  non-markdown assets without a canonical counterpart.
    runtime_state: (currently unused for the rules surface; reserved for
                   parity with ``_classify_chore_file``.)

    Signature-compatible with :func:`gzkit.chores._classify_chore_file`. See
    ``.gzkit/rules/skill-surface-sync.md`` § class-classifier.
    """
    path = Path(path)
    name = path.name
    parts = path.parts
    path_posix = path.as_posix()

    # package_only: __init__.py and __pycache__
    if name == "__init__.py" or "__pycache__" in parts:
        return "package_only"

    # Already under .gzkit/rules/ -> canonical (authored side)
    if ".gzkit/rules/" in path_posix:
        return "canonical"

    # Markdown rule files are canonical by default.
    if name.endswith(".md"):
        return "canonical"

    # For Python modules and non-markdown assets under src/gzkit/rules/,
    # resolve a counterpart at .gzkit/rules/<rel> when project_root is known.
    if project_root is not None:
        try:
            rel = path.relative_to(project_root / "src" / "gzkit" / "rules")
        except ValueError:
            rel = None
        if rel is not None:
            counterpart = project_root / ".gzkit" / "rules" / rel
            return "canonical" if counterpart.exists() else "package_only"

    # Fallback when project_root is not provided: resolve relative to CWD
    # when the path lives under src/gzkit/rules/.
    if "src/gzkit/rules/" in path_posix:
        cwd_root = Path.cwd()
        try:
            rel = path.relative_to(cwd_root / "src" / "gzkit" / "rules")
        except ValueError:
            # Try interpreting the input as repo-relative (e.g. when the
            # caller passes a path like Path("src/gzkit/rules/foo.json")
            # without an absolute root).
            try:
                rel = path.relative_to(Path("src/gzkit/rules"))
            except ValueError:
                rel = None
        if rel is not None:
            counterpart = cwd_root / ".gzkit" / "rules" / rel
            return "canonical" if counterpart.exists() else "package_only"

    return "package_only"


class ClassifiedRule(BaseModel):
    """An instruction rule with audience classification."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    filename: str = Field(..., description="Source instruction filename")
    audience: str = Field("shared", description="shared or claude-only")
    apply_to: str = Field(..., description="Raw applyTo frontmatter value")
    body: str = Field(..., description="Rule body content after frontmatter")
    is_global: bool = Field(..., description="Whether the rule applies globally")
    subtree_prefixes: list[str] = Field(
        default_factory=list, description="Directory prefixes for subtree rules"
    )


# ---------------------------------------------------------------------------
# Extracted from sync.py (lines 1181-1244)
# ---------------------------------------------------------------------------


def _skip_leading_comments(lines: list[str]) -> list[str]:
    """Skip leading HTML comments and blank lines before YAML frontmatter."""
    for idx, raw in enumerate(lines):
        stripped = raw.strip()
        if stripped == "---":
            return lines[idx:]
        if stripped.startswith("<!--") and stripped.endswith("-->"):
            continue
        if not stripped:
            continue
        break
    return lines


def _parse_instruction_frontmatter(content: str) -> dict[str, str]:
    """Parse frontmatter from an instruction file.

    Args:
        content: Full file content.

    Returns:
        Dictionary of frontmatter key-value pairs.

    """
    lines = _skip_leading_comments(content.splitlines())
    if not lines or lines[0].strip() != "---":
        return {}

    fm: dict[str, str] = {}
    for raw in lines[1:]:
        stripped = raw.strip()
        if stripped == "---":
            break
        if not stripped or ":" not in stripped:
            continue
        key, value = stripped.split(":", 1)
        fm[key.strip()] = value.strip().strip("\"'")
    return fm


def _extract_body_after_frontmatter(content: str) -> str:
    """Return the body content after YAML frontmatter.

    Args:
        content: Full file content.

    Returns:
        Body text after the closing --- delimiter.

    """
    lines = _skip_leading_comments(content.splitlines())
    if not lines or lines[0].strip() != "---":
        return content

    for idx, raw in enumerate(lines[1:], start=1):
        if raw.strip() == "---":
            return "\n".join(lines[idx + 1 :])
    return content


def _convert_apply_to_paths(apply_to: str) -> list[str]:
    """Convert Copilot applyTo string to Claude paths list.

    Args:
        apply_to: Comma-separated glob patterns.

    Returns:
        List of trimmed glob patterns.

    """
    patterns = [p.strip() for p in apply_to.split(",") if p.strip()]

    for pattern in patterns:
        if any(c in pattern for c in "{}!"):
            _logger.warning(
                "Glob pattern %r contains brace expansion or negation "
                "which may not be supported by Claude Code paths matcher.",
                pattern,
            )

    return patterns


# ---------------------------------------------------------------------------
# Classification helpers
# ---------------------------------------------------------------------------


def _is_global_pattern(pattern: str) -> bool:
    """Check if a glob pattern is global (starts with **)."""
    return pattern.startswith("**")


def _extract_subtree_prefix(pattern: str) -> str | None:
    """Extract the directory prefix from a subtree glob pattern.

    For ``tests/**`` returns ``tests``.
    For ``src/airlineops/warehouse/**`` returns ``src/airlineops/warehouse``.
    Returns None for global patterns like ``**/*``.
    Returns None for literal file paths with no glob segments (GHI #142) —
    a pattern with no wildcards is a file path, not a subtree prefix.
    """
    if _is_global_pattern(pattern):
        return None
    parts = pattern.replace("\\", "/").split("/")
    prefix_parts: list[str] = []
    saw_wildcard = False
    for part in parts:
        if "*" in part or "?" in part:
            saw_wildcard = True
            break
        prefix_parts.append(part)
    if not saw_wildcard:
        return None
    return "/".join(prefix_parts) if prefix_parts else None


_VENDOR_MIRROR_ROOTS: tuple[str, ...] = (
    ".claude",
    ".agents",
    ".github/instructions",
    ".github/skills",
)


def _is_vendor_mirror_prefix(prefix: str) -> bool:
    """Return True for prefixes that name a vendor-rendered output surface.

    Vendor mirrors (.claude, .agents, .github/instructions, .github/skills)
    are destinations gz writes generated content into — they are not
    user-authored subtrees that take nested AGENTS.md guidance. A meta-rule
    whose paths enumerate the vendor mirror it is itself rendered into
    (e.g. skill-surface-sync includes .github/instructions/**) creates a
    self-referential subtree the validator must waive (GHI #375).
    """
    normalized = prefix.replace("\\", "/").strip("/")
    return any(
        normalized == mirror or normalized.startswith(mirror + "/")
        for mirror in _VENDOR_MIRROR_ROOTS
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def classify_instruction_rules(project_root: Path) -> list[ClassifiedRule]:
    """Read and classify all instruction files by audience.

    Args:
        project_root: Project root directory.

    Returns:
        List of classified rules.

    """
    instructions_dir = project_root / ".github" / "instructions"
    if not instructions_dir.exists():
        return []

    rules: list[ClassifiedRule] = []
    for src_file in sorted(instructions_dir.iterdir()):
        if not src_file.name.endswith(".instructions.md"):
            continue

        content = src_file.read_text(encoding="utf-8")
        fm = _parse_instruction_frontmatter(content)

        exclude = fm.get("excludeAgent", "")
        if exclude in ("coding-agent", "all"):
            continue

        apply_to = fm.get("applyTo", "")
        if not apply_to:
            continue

        audience = fm.get("audience", "shared")
        body = _extract_body_after_frontmatter(content)

        patterns = _convert_apply_to_paths(apply_to)
        is_global = all(_is_global_pattern(p) for p in patterns)

        subtree_prefixes: list[str] = []
        if not is_global:
            for p in patterns:
                prefix = _extract_subtree_prefix(p)
                if prefix is None or _is_vendor_mirror_prefix(prefix):
                    continue
                if prefix not in subtree_prefixes:
                    subtree_prefixes.append(prefix)

        rules.append(
            ClassifiedRule(
                filename=src_file.name,
                audience=audience,
                apply_to=apply_to,
                body=body,
                is_global=is_global,
                subtree_prefixes=subtree_prefixes,
            )
        )

    return rules


def sync_claude_rules(project_root: Path, config: GzkitConfig | None = None) -> list[str]:
    """Mirror .github/instructions/*.instructions.md to .claude/rules/*.md.

    Uses config.paths.claude_rules instead of hardcoded path.

    Args:
        project_root: Project root directory.
        config: Optional project configuration.

    Returns:
        List of mirrored file paths (relative to project_root).

    """
    if config is None:
        config = GzkitConfig.load(project_root / ".gzkit.json")

    instructions_dir = project_root / ".github" / "instructions"
    rules_dir = project_root / config.paths.claude_rules
    ensure_dir(rules_dir)

    updated: list[str] = []
    expected_names: set[str] = set()

    if instructions_dir.exists():
        for src_file in sorted(instructions_dir.iterdir()):
            if not src_file.name.endswith(".instructions.md"):
                continue

            content = src_file.read_text(encoding="utf-8")
            fm = _parse_instruction_frontmatter(content)

            exclude = fm.get("excludeAgent", "")
            if exclude in ("coding-agent", "all"):
                continue

            apply_to = fm.get("applyTo", "")
            if not apply_to:
                _logger.warning("Skipping %s: no applyTo frontmatter.", src_file.name)
                continue

            body = _extract_body_after_frontmatter(content)
            target_name = src_file.name.replace(".instructions.md", ".md")
            expected_names.add(target_name)

            if apply_to.strip() == "**/*":
                output = body.lstrip("\n")
            else:
                paths = _convert_apply_to_paths(apply_to)
                paths_yaml = "\n".join(f'  - "{p}"' for p in paths)
                output = f"---\npaths:\n{paths_yaml}\n---\n{body}"

            target = rules_dir / target_name
            write_text_if_changed(target, output)
            updated.append(target.relative_to(project_root).as_posix())

    if rules_dir.exists():
        for existing in rules_dir.iterdir():
            if existing.is_file() and existing.name not in expected_names:
                remove_if_present(existing)

    return updated


def _classify_canonical_rules(project_root: Path) -> list[ClassifiedRule]:
    """Classify rules straight from ``.gzkit/rules/`` canon.

    Equivalent to :func:`classify_instruction_rules` BY CONSTRUCTION, not by
    resemblance: ``apply_to`` is built the same way
    :func:`render_rule_for_copilot` builds it, and the same
    ``_convert_apply_to_paths`` / ``_is_global_pattern`` /
    ``_extract_subtree_prefix`` helpers do the rest. The copilot rendering emits
    only ``applyTo``, so ``audience`` and ``excludeAgent`` are already absent
    from every canon-rendered instruction file and their defaults here lose
    nothing.
    """
    canonical_dir = project_root / ".gzkit" / "rules"
    if not canonical_dir.is_dir():
        return []
    classified: list[ClassifiedRule] = []
    for rule in load_rules(canonical_dir):
        apply_to = ", ".join(rule.frontmatter.paths)
        patterns = _convert_apply_to_paths(apply_to)
        is_global = all(_is_global_pattern(p) for p in patterns)
        subtree_prefixes: list[str] = []
        if not is_global:
            for pattern in patterns:
                prefix = _extract_subtree_prefix(pattern)
                if prefix is None or _is_vendor_mirror_prefix(prefix):
                    continue
                if prefix not in subtree_prefixes:
                    subtree_prefixes.append(prefix)
        classified.append(
            ClassifiedRule(
                filename=f"{rule.frontmatter.id.replace('-', '_')}.instructions.md",
                audience="shared",
                apply_to=apply_to,
                # `_RENDER_HEADER` prefix, exactly as `render_rule_for_copilot`
                # emits it: the body that reached this classifier used to be the
                # RENDERED file's, header included, and nested `AGENTS.md`
                # embedded that header per section. Dropping it would be a
                # cosmetic improvement and a 92-line churn across 29 generated
                # surfaces, which is not this GHI's business. Byte-identical
                # output keeps the equivalence claim exact rather than
                # "equivalent apart from a marker".
                body=f"{_RENDER_HEADER}\n{rule.body}",
                is_global=is_global,
                subtree_prefixes=subtree_prefixes,
            )
        )
    return classified


def _shared_subtree_rules(project_root: Path) -> dict[str, list[ClassifiedRule]]:
    """Group shared, non-global rules by the subtree each one applies to.

    Canon first (GHI #891). This used to read ONLY ``.github/instructions/`` --
    a GENERATED surface -- to decide what to generate, held together by an
    ordering comment in ``sync_all`` asking the caller to render Copilot rules
    first. A derived view feeding a derived view is what ``AGENTS.md``
    § Architectural Boundaries #6 forbids, and it made ``sync_all``
    unable to render without first writing: under a capture sink the instruction
    files are not on disk, classification came back empty, and all 14 nested
    ``AGENTS.md`` silently vanished from the plan.

    The instruction-file path remains as the fallback for trees with no
    ``.gzkit/rules/`` canon -- an adopter hand-authoring ``.github/instructions/``
    directly -- where those files ARE the source rather than a rendering of one.
    """
    canonical = _classify_canonical_rules(project_root)
    rules = canonical if canonical else classify_instruction_rules(project_root)
    subtree_rules: dict[str, list[ClassifiedRule]] = {}
    for rule in rules:
        if rule.audience != "shared" or rule.is_global:
            continue
        for prefix in rule.subtree_prefixes:
            subtree_rules.setdefault(prefix, []).append(rule)
    return subtree_rules


_CLAUDE_REDIRECT_BODY = (
    f"{_GENERATED_MARKER}\n"
    "# {subtree} Agent Instructions (Claude)\n\n"
    "> Claude discovers nested instruction files as `CLAUDE.md`; the shared\n"
    "> subtree rules live in the sibling `AGENTS.md`. This file imports them so\n"
    "> either harness reads the same governance surface (GHI #923).\n\n"
    "@AGENTS.md\n"
)


def _subtree_sections(rules_for_subtree: list[ClassifiedRule]) -> list[str]:
    """Rule bodies that will render into a subtree's ``AGENTS.md``.

    One predicate for "does this subtree get a file", shared by the writer and
    by :func:`nested_agents_md_paths`. Two copies would drift on the
    empty-body case, and the helper under-reporting the writer is the class of
    defect GHI #890 closed.
    """
    return [body for rule in rules_for_subtree if (body := rule.body.strip())]


def _foreign_vendor_roots(project_root: Path, config: GzkitConfig) -> tuple[Path, ...]:
    """Surface roots belonging to a vendor other than Claude.

    A Claude redirect is not written inside one: those trees carry their own
    vendor's discovery convention, and seeding another vendor's root with
    ``CLAUDE.md`` claims a surface gzkit does not own there. Derived from the
    declared vendor set rather than a literal list, so retiring a vendor
    removes its root here in the same edit.
    """
    vendors = config.vendors
    return tuple(
        project_root / vendor.surface_root
        for name in type(vendors).model_fields
        if name != "claude" and (vendor := getattr(vendors, name)).surface_root
    )


def _within_any(path: Path, roots: tuple[Path, ...]) -> bool:
    """Whether *path* is one of *roots* or nested beneath one."""
    return any(path == root or root in path.parents for root in roots)


def _nested_subtrees(project_root: Path) -> list[tuple[str, Path, list[str]]]:
    """``(subtree, subtree_dir, sections)`` for every subtree that gets a file.

    The single walk both :func:`sync_nested_agents_md` and
    :func:`nested_agents_md_paths` read, so the write set and the writer cannot
    disagree about which directories are in play.
    """
    found: list[tuple[str, Path, list[str]]] = []
    for subtree, rules_for_subtree in sorted(_shared_subtree_rules(project_root).items()):
        subtree_dir = project_root / subtree
        # `dir_exists`, not `is_dir`: inside a captured sync the directory an
        # earlier pass would create is not on disk yet, and `is_dir` would answer
        # about the PRE-sync tree -- silently dropping `.gzkit/skills/AGENTS.md`
        # from the plan (GHI #891).
        if dir_exists(subtree_dir):
            found.append((subtree, subtree_dir, _subtree_sections(rules_for_subtree)))
    return found


def nested_agents_md_paths(project_root: Path, config: GzkitConfig | None = None) -> set[Path]:
    """Every nested path :func:`sync_nested_agents_md` may write.

    Covers both surfaces it emits: the subtree ``AGENTS.md`` and the sibling
    ``CLAUDE.md`` redirect (GHI #923). Derived from the same walk the writer
    uses, so a caller that must know the write set cannot fall out of step with
    it. Callers that snapshot before a sync (``validate_pkg.sync_parity``) need
    exactly this set: a hand-maintained list is what let ``gz validate
    --surfaces`` leave 16 files modified after a read-only run — the tuple named
    3 paths while the writer touched ~19, so restore could only put back the 3
    it knew about.
    """
    if config is None:
        config = GzkitConfig.load(project_root / ".gzkit.json")
    foreign = _foreign_vendor_roots(project_root, config)
    paths: set[Path] = set()
    for _subtree, subtree_dir, sections in _nested_subtrees(project_root):
        paths.add(subtree_dir / "AGENTS.md")
        if sections and not _within_any(subtree_dir, foreign):
            paths.add(subtree_dir / "CLAUDE.md")
    return paths


def sync_nested_agents_md(project_root: Path, config: GzkitConfig | None = None) -> list[str]:
    """Generate nested AGENTS.md files for shared subtree rules.

    Args:
        project_root: Project root directory.
        config: Optional project configuration.

    Returns:
        List of nested AGENTS.md file paths (relative to project_root).

    """
    if config is None:
        config = GzkitConfig.load(project_root / ".gzkit.json")

    foreign = _foreign_vendor_roots(project_root, config)

    updated: list[str] = []
    expected_paths: set[Path] = set()
    expected_redirects: set[Path] = set()

    # `_nested_subtrees` carries the `dir_exists` guard that `nested_agents_md_paths`
    # also reads. The two MUST ask the same question: the helper exists so a caller
    # can know this writer's write set, and a guard that differs by even one
    # predicate reintroduces the drift GHI #890 closed. Under a capture sink an
    # earlier pass's directory is recorded rather than created, so a bare `is_dir`
    # dropped `src/AGENTS.md` from the plan while apply mode still wrote it.
    for subtree, subtree_dir, sections in _nested_subtrees(project_root):
        agents_path = subtree_dir / "AGENTS.md"
        expected_paths.add(agents_path)

        if not sections:
            continue

        content = (
            f"{_GENERATED_MARKER}\n"
            f"# {subtree} Agent Instructions\n\n"
            "> Shared subtree rules. See root `AGENTS.md` for project-wide governance.\n\n"
            + "\n\n".join(sections)
            + "\n"
        )

        write_text_if_changed(agents_path, content)
        updated.append(agents_path.relative_to(project_root).as_posix())

        # Claude discovers nested instruction files as CLAUDE.md, so the subtree
        # rules above reach Codex alone without this redirect (GHI #923). An
        # import rather than a copy: two renderings of one rule set can disagree
        # after a later sync, and the root surface already establishes the
        # pattern (`CLAUDE.md` -> `@AGENTS.md`, GHI #525).
        if _within_any(subtree_dir, foreign):
            continue
        redirect_path = subtree_dir / "CLAUDE.md"
        expected_redirects.add(redirect_path)
        write_text_if_changed(redirect_path, _CLAUDE_REDIRECT_BODY.format(subtree=subtree))
        updated.append(redirect_path.relative_to(project_root).as_posix())

    mirror_roots = _mirror_owned_roots(project_root, config)
    _cleanup_stale_nested_agents(project_root, expected_paths, mirror_roots)
    _cleanup_stale_nested_agents(
        project_root, expected_redirects, mirror_roots, filename="CLAUDE.md"
    )

    return updated


def _mirror_owned_roots(project_root: Path, config: GzkitConfig) -> tuple[tuple[Path, Path], ...]:
    """``(mirror_root, canonical_root)`` pairs whose ``AGENTS.md`` files are copies.

    ``sync_skill_mirror`` copies the canonical skills tree into each vendor
    path, and ``sync_pkg_surfaces`` copies it into the wheel-shipping package
    tree. The canonical root travels with each mirror because a copy is only
    stale when its SOURCE is gone -- excluding mirror trees outright would keep
    them from churning but would also orphan a copy forever once the canonical
    file it mirrors is retired, and ``sync_skill_mirror`` is documented as
    "intentionally additive/non-destructive", so nothing else would remove it.
    """
    canonical = project_root / config.paths.skills
    mirrors = (
        config.paths.claude_skills,
        config.paths.copilot_skills,
        config.paths.codex_skills,
        "src/gzkit/skills",
    )
    pairs = {
        (project_root / rel, canonical)
        for rel in mirrors
        if rel and project_root / rel != canonical
    }
    return tuple(sorted(pairs))


def _mirror_root_for(
    agents_file: Path, mirror_roots: tuple[tuple[Path, Path], ...]
) -> tuple[Path, Path] | None:
    """Return the ``(mirror_root, canonical_root)`` pair owning ``agents_file``."""
    for pair in mirror_roots:
        if agents_file.is_relative_to(pair[0]):
            return pair
    return None


def _cleanup_stale_nested_agents(
    project_root: Path,
    expected_paths: set[Path],
    mirror_roots: tuple[tuple[Path, Path], ...] = (),
    filename: str = "AGENTS.md",
) -> None:
    """Remove nested *filename* files not in the expected set.

    ``filename`` selects the surface swept -- ``AGENTS.md`` for the subtree
    rules themselves, ``CLAUDE.md`` for the Claude redirects beside them
    (GHI #923). One sweep serves both because the mirror-exclusion policy below
    is a property of the TREE, not of the name: a redirect copied into
    ``.claude/skills/`` by the mirror pass is exactly as marker-bearing and
    exactly as absent from ``expected_paths`` as a copied ``AGENTS.md``, so a
    second sweep written without this policy would re-open the GHI #890 churn
    under the new name.

    Only deletes files bearing the gzkit generated marker, and never removes a
    mirror copy whose canonical source survives -- those trees belong to the
    skill and package mirror writers.

    The exclusion is load-bearing rather than defensive. A canonical nested
    ``AGENTS.md`` carries the generated marker, so every mirror copy of it
    carries the marker too while never appearing in ``expected_paths``.
    Scanning the whole project therefore deleted six mirrored files on each
    sync -- ``.claude/skills/``, ``.agents/skills/``, ``.github/skills/`` --
    which the mirror pass re-created moments later. The final tree looks
    untouched, so neither ``git status`` nor a bytes comparison shows it; what
    it actually does is briefly remove a governance surface and rewrite it on
    every run (GHI #890).

    Deletion is decided for the whole sweep before any file is unlinked.
    Deciding as it walks makes the outcome depend on ``rglob`` order: a
    canonical file and its mirror are both marker-bearing, so visiting the
    canonical first deletes it and leaves the mirror looking like an orphan,
    while visiting the mirror first spares it. Same tree, two results.
    """
    root_agents = project_root / filename
    candidates = [
        path
        for path in project_root.rglob(filename)
        if path != root_agents and path not in expected_paths
    ]
    surviving_canonicals = {path for path in candidates if not _mirror_root_for(path, mirror_roots)}
    for agents_file in candidates:
        pair = _mirror_root_for(agents_file, mirror_roots)
        if pair is not None:
            mirror_root, canonical_root = pair
            counterpart = canonical_root / agents_file.relative_to(mirror_root)
            # A copy is stale only when its source is gone -- either absent now,
            # or slated for removal by this same sweep.
            if counterpart.is_file() and counterpart not in surviving_canonicals:
                continue
        try:
            first_line = agents_file.read_text(encoding="utf-8").split("\n", 1)[0]
            if "Generated by gzkit" in first_line:
                remove_if_present(agents_file)
        except (OSError, UnicodeDecodeError):
            pass


def validate_rule_placement(project_root: Path) -> list[str]:
    """Check for misplaced rules.

    Args:
        project_root: Project root directory.

    Returns:
        List of warning messages.

    """
    warnings: list[str] = []
    rules = classify_instruction_rules(project_root)

    claude_rules_dir = project_root / ".claude" / "rules"

    for rule in rules:
        if rule.audience == "claude-only":
            target_name = rule.filename.replace(".instructions.md", ".md")
            if not (claude_rules_dir / target_name).exists():
                warnings.append(
                    f"{rule.filename}: audience is claude-only but not mirrored to .claude/rules/"
                )
        elif rule.audience == "shared" and not rule.is_global:
            for prefix in rule.subtree_prefixes:
                subtree_dir = project_root / prefix
                agents_path = subtree_dir / "AGENTS.md"
                if subtree_dir.exists() and not agents_path.exists():
                    warnings.append(
                        f"{rule.filename}: shared subtree rule for '{prefix}' "
                        f"has no nested AGENTS.md"
                    )

    return warnings


# ---------------------------------------------------------------------------
# Canonical rule loading (.gzkit/rules/)
# ---------------------------------------------------------------------------


class RuleFrontmatter(BaseModel):
    """Vendor-neutral rule frontmatter schema.

    Every canonical rule in ``.gzkit/rules/`` must have this frontmatter.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    id: str = Field(..., description="Rule identifier (kebab-case, e.g., 'governance-core')")
    paths: list[str] = Field(
        ..., description="Glob patterns for files this rule applies to", min_length=1
    )
    description: str = Field(..., description="One-line description of the rule's purpose")


class CanonicalRule(BaseModel):
    """A loaded canonical rule: validated frontmatter plus body content."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    frontmatter: RuleFrontmatter = Field(..., description="Validated rule frontmatter")
    body: str = Field(..., description="Markdown body content (after frontmatter)")
    source_path: str = Field(..., description="Path to the source .md file")


def _parse_canonical_frontmatter(path: Path) -> tuple[dict[str, Any], str]:
    """Parse a canonical rule file into (frontmatter_dict, body).

    Raises ValueError if frontmatter delimiters are missing.
    """
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        msg = f"Rule file missing frontmatter delimiter: {path}"
        raise ValueError(msg)

    parts = text.split("---", 2)
    if len(parts) < 3:
        msg = f"Rule file has unclosed frontmatter: {path}"
        raise ValueError(msg)

    fm_text = parts[1].strip()
    body = parts[2].strip()

    fm_dict: dict[str, Any] = yaml.safe_load(fm_text) or {}
    return fm_dict, body


def load_rule(path: Path) -> CanonicalRule:
    """Load and validate a single canonical rule file.

    Raises ValueError for parse errors, pydantic.ValidationError for
    invalid frontmatter.
    """
    fm_dict, body = _parse_canonical_frontmatter(path)
    frontmatter = RuleFrontmatter(**fm_dict)
    return CanonicalRule(
        frontmatter=frontmatter,
        body=body,
        source_path=str(path),
    )


def load_rules(rules_dir: Path) -> list[CanonicalRule]:
    """Load and validate all canonical rules from a directory.

    Returns a list of validated CanonicalRule objects sorted by rule ID.
    Raises ValueError if the directory does not exist.
    Raises pydantic.ValidationError if any rule has invalid frontmatter.
    """
    if not rules_dir.is_dir():
        msg = f"Rules directory does not exist: {rules_dir}"
        raise ValueError(msg)

    rules: list[CanonicalRule] = []
    for md_file in sorted(rules_dir.glob("*.md")):
        if md_file.name in NESTED_SURFACE_NAMES:
            continue
        rules.append(load_rule(md_file))

    return sorted(rules, key=lambda r: r.frontmatter.id)


# ---------------------------------------------------------------------------
# Vendor-specific rule rendering (canonical → vendor shape)
# ---------------------------------------------------------------------------

_RENDER_HEADER = "<!-- Generated by gz agent sync — do not edit -->\n"


def render_rule_for_claude(rule: CanonicalRule) -> str:
    """Render a canonical rule into Claude rules format.

    Global rules (paths: ["**/*"]) omit the frontmatter block.
    Scoped rules get ``paths:`` YAML frontmatter on line 1 — Claude
    Code's parser falls back to unconditional load when anything
    (HTML comment included) precedes the opening ``---``.
    """
    is_global = rule.frontmatter.paths == ["**/*"]
    if is_global:
        return f"{_RENDER_HEADER}\n{rule.body}\n"
    paths_yaml = "\n".join(f'  - "{p}"' for p in rule.frontmatter.paths)
    return f"---\npaths:\n{paths_yaml}\n---\n{_RENDER_HEADER}\n{rule.body}\n"


def render_rule_for_copilot(rule: CanonicalRule) -> str:
    """Render a canonical rule into Copilot instructions format.

    Produces ``applyTo:`` frontmatter on line 1; the generator header
    follows the closing ``---`` so the frontmatter parser sees a
    well-formed block (same constraint as Claude rules).
    """
    apply_to = ", ".join(rule.frontmatter.paths)
    return f'---\napplyTo: "{apply_to}"\n---\n{_RENDER_HEADER}\n{rule.body}\n'


def _render_path_str(target: Path, project_root: Path | None) -> str:
    """Render a written path as a project-relative posix string when possible.

    Mirrors ``plan_sync_all``'s normalization so apply mode and dry-run agree.
    """
    if project_root is None:
        return str(target)
    try:
        return target.relative_to(project_root).as_posix()
    except ValueError:
        return target.as_posix()


#: Path prefixes only the gzkit repository can satisfy. `src/gzkit/` is the
#: package source -- an adopter installs py-gzkit as a dependency and never
#: vendors it. `scripts/` and `data/` are this repo's own registries and
#: harnesses (`scripts/session_orientation.py`, `data/exemplar_corpus.json`,
#: `data/security_surfaces.json`); `gz init` scaffolds neither.
#:
#: `.gzkit/` is deliberately ABSENT and that is the load-bearing distinction:
#: it is the governance directory of WHOEVER RUNS GZ, so `.gzkit/handoffs/**`
#: and `.gzkit/locks/exchange/**` are adopter-real. A first classification of
#: this corpus matched the literal "gzkit" and reported four rules as wholly
#: framework-internal; three were false for exactly this reason.
_FRAMEWORK_INTERNAL_PREFIXES = ("src/gzkit/", "scripts/", "data/")


def _is_framework_internal_path(path: str) -> bool:
    """Return whether ``path`` names something only the gzkit repo can have."""
    return path.startswith(_FRAMEWORK_INTERNAL_PREFIXES)


def _is_framework_tree(project_root: Path | None) -> bool:
    """Return whether ``project_root`` IS gzkit rather than a project using it.

    Keyed on the package source being present in the tree, which is true of this
    repository and of nothing else: an adopter depends on py-gzkit and does not
    carry `src/gzkit/`. Derived from the root PASSED IN, never an ambient one --
    the discipline `_ruff_format_dir` learned under GHI #909.

    ``None`` means the caller did not say, and the conservative answer is "yes,
    the framework": it preserves today's rendering exactly rather than silently
    stripping scope from a caller that never opted in.
    """
    if project_root is None:
        return True
    return (project_root / "src" / "gzkit" / "__init__.py").is_file()


def _scope_rule_for_delivery(
    rule: CanonicalRule, project_root: Path | None
) -> CanonicalRule | None:
    """Narrow a rule's paths to what the delivery target can actually have.

    gzkit's canonical rules serve TWO consumers -- this repository and every
    adopter -- and `paths:` can only say one thing. Scrubbing the canonical
    frontmatter would fix adopters by degrading the framework: strip
    `src/gzkit/mx/**` from mx-mode and gzkit stops scoping that rule to the code
    it governs. Filtering at the delivery boundary keeps the canonical rule whole
    and lets each consumer see the scopes that mean something to it (GHI #911).

    Returns ``None`` when nothing adopter-real survives. A rule scoped to nothing
    is not a smaller rule, it is noise: `RuleFrontmatter.paths` carries
    ``min_length=1`` precisely because an unscoped rule is not a rule. Exactly
    one canonical rule is in that position today (`cli`, scoping only
    `src/gzkit/commands/**`).

    This mirrors `_prune_unshippable_chores` (GHI #783) one level down, including
    its reason for keying on a classifier: the class definition is the contract,
    and a glob restating one shape of it would drift.
    """
    if _is_framework_tree(project_root):
        return rule
    deliverable = [p for p in rule.frontmatter.paths if not _is_framework_internal_path(p)]
    if not deliverable:
        return None
    if deliverable == rule.frontmatter.paths:
        return rule
    return rule.model_copy(
        update={"frontmatter": rule.frontmatter.model_copy(update={"paths": deliverable})}
    )


def render_rules_to_dir(
    rules: list[CanonicalRule],
    target_dir: Path,
    renderer: str,
    project_root: Path | None = None,
) -> list[str]:
    """Render canonical rules to a target directory.

    Args:
        rules: Loaded canonical rules.
        target_dir: Output directory (e.g., .claude/rules/ or .github/instructions/).
        renderer: "claude" or "copilot".
        project_root: When given, returned paths are rendered relative to it
            (forward-slash posix). ``sync_all`` passes this so every path in its
            write set has the same project-relative form — apply mode prints the
            list verbatim while dry-run (``plan_sync_all``) normalizes, so a
            mixed absolute/relative return made the two diverge for rule files
            (the macOS-passes / Linux-fails coverage hole this closes).

    Returns:
        List of written file paths — project-relative posix strings when
        ``project_root`` is given, else absolute strings.

    """
    ensure_dir(target_dir)

    render_fn = render_rule_for_claude if renderer == "claude" else render_rule_for_copilot
    suffix = ".md" if renderer == "claude" else ".instructions.md"
    name_fn = (
        (lambda r: f"{r.frontmatter.id.replace('_', '-')}{suffix}")
        if renderer == "claude"
        else (lambda r: f"{r.frontmatter.id.replace('-', '_')}{suffix}")
    )

    written: list[str] = []
    expected_names: set[str] = set()

    for rule in rules:
        deliverable = _scope_rule_for_delivery(rule, project_root)
        if deliverable is None:
            # Wholly framework-internal: not delivered, and deliberately NOT added
            # to expected_names, so the stale sweep below removes a copy an
            # earlier version of this renderer wrote (GHI #911).
            continue
        filename = name_fn(deliverable)
        expected_names.add(filename)
        output = render_fn(deliverable)
        target = target_dir / filename
        write_text_if_changed(target, output)
        written.append(_render_path_str(target, project_root))

    # Guarded rather than an unguarded walk: `ensure_dir` above is a no-op under
    # a capture sink, and a stale-file sweep over a directory that does not exist
    # has nothing to sweep. The old snapshot envelope hid this -- sync CREATED an
    # empty `.github/instructions` on every parity check and the restore removed
    # it again, so that mkdir was load-bearing by accident.
    for existing in sorted(target_dir.iterdir()) if target_dir.is_dir() else ():
        if existing.is_file() and existing.name not in expected_names:
            try:
                content = existing.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                continue
            if "Generated by gz agent sync" in content:
                remove_if_present(existing)

    return written


# Re-export scaffolding API so `from gzkit.rules import X` works.
from gzkit.rules._scaffolder import (  # noqa: E402
    CORE_RULES,
    _iter_canonical_rule_slugs,
    scaffold_core_rules,
)

__all__ = [
    "CORE_RULES",
    "CanonicalRule",
    "ClassifiedRule",
    "RuleFrontmatter",
    "_classify_rule_file",
    "_is_framework_internal_path",
    "_iter_canonical_rule_slugs",
    "classify_instruction_rules",
    "load_rule",
    "load_rules",
    "render_rule_for_claude",
    "render_rule_for_copilot",
    "render_rules_to_dir",
    "scaffold_core_rules",
    "sync_claude_rules",
    "NESTED_SURFACE_NAMES",
    "nested_agents_md_paths",
    "sync_nested_agents_md",
    "validate_rule_placement",
]
