"""Deprecated-verb prescription audit (GHI #705).

`gz validate --deprecated-verb-prescription` fails closed when a `gz` verb that
announces its own deprecation at runtime is still **prescribed** by a governed
surface — a binding rule, a skill, or a runbook.

The instance: `gz gates` printed *"will be removed in a future release. Use
`gz closeout` instead."* while `.gzkit/rules/governance-core.md` named it as
step 5 of the required workflow order and an `lifecycle_state: active` skill
wrapped it. An agent following the rule literally was routed onto a deprecated
surface with no signal that the correct move was a different verb entirely.

`.gzkit/rules/tool-skill-runbook-alignment.md` Invariant 2 requires a skill's
`gz_command` to resolve to a verb the runbook prescribes for that operator
moment. Nothing checked the inverse — that neither still prescribes a verb the
CLI has *retired*. This scope is that inverse.

**Scanned surfaces** are the governed path only: canonical rules and skills
under `.gzkit/`, their package sources under `src/gzkit/`, the two runbooks, and
the root agent-contract files. Vendor mirrors (`.claude/`, `.agents/`,
`.github/`) are regenerated by `gz agent sync control-surfaces` and follow their
canonical source, so scanning them would trip three findings for one edit.
Historical record — `RELEASE_NOTES.md`, ADR packages under `docs/design/` — is
never scanned: a deprecated verb named there is a true statement about the past,
not a live prescription.

**Escape marker.** A line carrying `deprecated-verb-ok` is skipped, so a rule
that *documents* a deprecation can name the verb without tripping the gate it
describes.

Failures emit ``ValidationError(type="deprecated_verb_prescription", ...)``;
a non-empty list maps to exit 3 in the orchestrator. A clean tree returns ``[]``.
"""

from __future__ import annotations

import re
from pathlib import Path

from gzkit.governance.deprecations import DEPRECATED_VERBS, DeprecatedVerb
from gzkit.validate import ValidationError

__all__ = ["audit_deprecated_verb_prescription"]

_ESCAPE_MARKER = "deprecated-verb-ok"

_SURFACE_GLOBS = (
    ".gzkit/rules/**/*.md",
    ".gzkit/skills/**/SKILL.md",
    "src/gzkit/rules/**/*.md",
    "src/gzkit/skills/**/SKILL.md",
)

_SURFACE_FILES = (
    "docs/user/runbook.md",
    "docs/governance/governance_runbook.md",
    "AGENTS.md",
    "CLAUDE.md",
)


def _pattern(entry: DeprecatedVerb) -> re.Pattern[str]:
    """Match ``gz <verb>`` as a command reference, not as a bare English word.

    The trailing boundary keeps ``gz gates`` from matching a longer live verb
    that merely starts with the same characters.
    """
    return re.compile(rf"\bgz\s+{re.escape(entry.verb)}\b")


def _governed_files(project_root: Path) -> list[Path]:
    seen: dict[Path, None] = {}
    for glob in _SURFACE_GLOBS:
        for path in sorted(project_root.glob(glob)):
            if path.is_file():
                seen.setdefault(path, None)
    for rel in _SURFACE_FILES:
        path = project_root / rel
        if path.is_file():
            seen.setdefault(path, None)
    return list(seen)


def _scan_file(path: Path, project_root: Path) -> list[ValidationError]:
    rel = path.relative_to(project_root).as_posix()
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return []
    errors: list[ValidationError] = []
    for lineno, line in enumerate(text.splitlines(), start=1):
        if _ESCAPE_MARKER in line:
            continue
        for entry in DEPRECATED_VERBS:
            if not _pattern(entry).search(line):
                continue
            errors.append(
                ValidationError(
                    type="deprecated_verb_prescription",
                    artifact=rel,
                    field=entry.verb,
                    message=(
                        f"{rel}: line {lineno} prescribes `gz {entry.verb}`, which the CLI "
                        f"announces as deprecated at runtime. A governed surface must never "
                        f"route an agent onto a retired verb "
                        f"(.gzkit/rules/tool-skill-runbook-alignment.md Invariant 2; GHI "
                        f"{entry.ghi}). Repoint the reference to `{entry.successor}`, or — if "
                        f"the line documents the deprecation rather than prescribing it — mark "
                        f"it with an inline `{_ESCAPE_MARKER}: <reason>` comment."
                    ),
                )
            )
    return errors


def audit_deprecated_verb_prescription(project_root: Path) -> list[ValidationError]:
    """Flag every governed-surface line that prescribes a deprecated `gz` verb."""
    errors: list[ValidationError] = []
    for path in _governed_files(project_root):
        errors.extend(_scan_file(path, project_root))
    return errors
