"""Render registered neutral role bodies into native Codex agent TOML.

Only captured legacy bodies and explicitly managed files are replaced. Native
metadata remains byte-for-byte intact; unknown and customized roles are owned
by the user. Writes use the shared capture sink for read-only sync planning.
"""

import hashlib
import json
import re
import tomllib
from pathlib import Path

from gzkit.surface_write import write_text_if_changed

MARKER = "# Generated by gzkit from .gzkit/agents; role body managed, metadata preserved."
_BODY_KEY = re.compile(
    r"(?m)^[ \t]*(?:developer_instructions|\"developer_instructions\""
    r"|'developer_instructions')[ \t]*="
)


def render_codex_role(source: str, body: str) -> str:
    """Replace one root string while proving every other TOML value survives.

    Try complete line spans instead of interpreting TOML string escapes. Parsing
    the candidate and comparing the whole document also rejects apparent keys
    embedded inside another multiline string or a nested table.
    """
    original = tomllib.loads(source)
    if not isinstance(original.get("developer_instructions"), str):
        raise ValueError("Codex role developer_instructions must be a string")
    expected = {**original, "developer_instructions": body}
    for match in _BODY_KEY.finditer(source):
        ends = [m.end() for m in re.finditer("\n", source[match.end() :])]
        for end in [*(match.end() + offset for offset in ends), len(source)]:
            candidate = (
                source[: match.start()]
                + "developer_instructions = "
                + json.dumps(body, ensure_ascii=False)
                + "\n"
                + source[end:]
            )
            try:
                parsed = tomllib.loads(candidate)
            except tomllib.TOMLDecodeError:
                continue
            if parsed == expected:
                return (
                    candidate if candidate.startswith(MARKER + "\n") else MARKER + "\n" + candidate
                )
    raise ValueError("Cannot safely replace Codex role developer_instructions")


def _role_output(root: Path, name: str, metadata: object) -> tuple[Path, str] | None:
    """Plan one registered role, leaving customized native bodies untouched."""
    if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", name) or not isinstance(metadata, dict):
        raise ValueError("Invalid canonical Codex role registration")
    description = metadata.get("description")
    digest = metadata.get("legacy_codex_body_sha256")
    if not isinstance(description, str) or not isinstance(digest, str):
        raise ValueError(f"Invalid canonical Codex role metadata: {name}")
    body = (root / ".gzkit/agents" / f"{name}.md").read_text(encoding="utf-8").strip()
    if not body:
        raise ValueError(f"Empty canonical Codex role: {name}")
    destination = root / ".codex/agents" / f"{name}.toml"
    if not destination.exists():
        source = f"name = {json.dumps(name)}\ndescription = {json.dumps(description)}\n"
        source += 'developer_instructions = ""\n'
    else:
        source = destination.read_text(encoding="utf-8")
        current = tomllib.loads(source).get("developer_instructions")
        if not isinstance(current, str):
            raise ValueError(f"Codex role developer_instructions must be a string: {name}")
        legacy = hashlib.sha256(current.strip().encode("utf-8")).hexdigest() == digest
        if not (source.startswith(MARKER + "\n") or legacy or current.strip() == body):
            return None
    return destination, render_codex_role(source, body)


def sync_codex_roles(project_root: Path) -> list[str]:
    """Sync registered roles; return all managed project-relative paths.

    No registry means no ownership and no writes. Preflight every role before
    applying any writes so an invalid registry, body, or native TOML fails cleanly.
    The caller decides whether Codex delivery is enabled for this project.
    """
    registry_path = project_root / ".gzkit/agents/roles.json"
    if not registry_path.exists():
        return []
    registry = json.loads(registry_path.read_text(encoding="utf-8"))
    if not isinstance(registry, dict) or registry.get("version") != 1:
        raise ValueError("Unsupported canonical Codex role registry")
    roles = registry.get("roles")
    if not isinstance(roles, dict):
        raise ValueError("Canonical Codex role registry requires a roles mapping")
    outputs = [
        _role_output(project_root, name, metadata) for name, metadata in sorted(roles.items())
    ]
    managed = []
    for output in outputs:
        if output is not None:
            path, content = output
            write_text_if_changed(path, content)
            managed.append(path.relative_to(project_root).as_posix())
    return managed
