"""Single authority for the OBPI-brief completion evidence rule (GHI #847).

The rule lives here, not in its callers, because it already had TWO copies —
``.claude/hooks/obpi-completion-validator.py`` (generated by
:func:`gzkit.hooks.scripts.validation._obpi_completion_validator_script`) and
``gzkit.commands.obpi_complete._validate_would_be_content``, whose own docstring
read *"Mirrors the checks in obpi-completion-validator.py hook"*. Two copies of a
completion gate is the two-copies-one-binds shape ``ADR-0.35.0`` exists to
remove: they can disagree about what counts as evidence, and the disagreement is
invisible because whichever locus the agent happens to reach is the one that
rules.

Three loci observe it, and they are deliberately not symmetric:

``.claude/hooks/obpi-completion-validator.py``
    PreToolUse, refusing the write before it lands. Bound to the
    ``Write|Edit|NotebookEdit`` matcher and keyed on ``tool_input.file_path`` —
    a field a Bash payload does not carry — so every ``sed`` / heredoc /
    inline-``python`` edit bypasses it entirely (GHI #844, measured 2026-08-21:
    348 Bash calls, 0 Write/Edit calls across three sessions). An advisory fast
    path, never the guarantee.

:func:`gzkit.hooks.guards.forbid_unattested_obpi_completion_commits`
    Pre-commit, reading ``git diff --cached``. It observes the **filesystem
    outcome**, so no tool choice evades it. This is the arm that binds.

:func:`gzkit.commands.obpi_complete._validate_would_be_content`
    The governed writer's own pre-flight, so ``gz obpi complete`` refuses with
    the same bar it will later be judged against.

Scope note: this fence governs the BRIEF's evidence sections. It is not Gate 5,
and it never substitutes for one — ``ADR-0.0.36`` makes brief-level human
attestation universal, and the ledger is what records it. A brief that *reads*
attested is necessary, never sufficient.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

#: Non-substantive section bodies. Lifted verbatim from the two prior copies so
#: the merge changes no verdict — a fence that quietly tightened while being
#: de-duplicated would be a second change wearing the first one's commit.
PLACEHOLDERS: frozenset[str] = frozenset(
    {
        "tbd",
        "todo",
        "...",
        "none",
        "(none)",
        "-",
        "n/a",
        "paste test output here",
        "paste lint/format/type check output here",
        "one-sentence concrete outcome",
        "<name>",
    }
)

#: Headings that can carry the proof, in preference order.
_PROOF_HEADINGS: tuple[str, ...] = ("Key Proof", "Verification", "Gate Evidence")

_STATUS_COMPLETED_PATTERNS: tuple[str, ...] = (
    r"\*\*(?:Brief\s+)?Status:\*\*\s*Completed",
    r"^(?:Brief\s+)?Status:\s*Completed",
    r"^\|\s*(?:Brief\s+)?Status\s*\|\s*Completed\s*\|",
)

#: Audit-ledger entry types that count as recorded completion evidence.
_AUDIT_TYPES: frozenset[str] = frozenset({"obpi-audit", "obpi-completion"})


def is_placeholder(text: str) -> bool:
    """Return True when *text* is a non-substantive placeholder."""
    clean = text.strip().lower()
    if not clean:
        return True
    if clean in PLACEHOLDERS:
        return True
    # Template bullet patterns: full-line "- Label:" or extracted label "Label:"
    if re.match(r"^-\s+\w[^:]*:\s*$", clean):
        return True
    if re.match(r"^[\w][\w\s/]*:\s*$", clean):
        return True
    return clean.startswith("<!--") and clean.endswith("-->")


def _section(content: str, heading: str) -> str | None:
    """Return an H3 section's body, bounded by the next H2 *or* H3.

    The ``#{2,3}`` boundary matters: an H3 that runs to the next H3 only would
    swallow a following H2's content and read a placeholder section as
    substantive.
    """
    match = re.search(
        rf"^### {re.escape(heading)}\s*$([\s\S]*?)(?:^#{{2,3}} |\n---|\Z)",
        content,
        flags=re.MULTILINE,
    )
    return match.group(1) if match else None


def is_obpi_brief_path(rel_path: str) -> bool:
    """Return True when *rel_path* is an OBPI brief this fence governs."""
    normalized = rel_path.replace("\\", "/")
    return "/obpis/OBPI-" in f"/{normalized.lstrip('/')}" and normalized.endswith(".md")


def marks_completed(content: str) -> bool:
    """Return True when *content* declares the brief Completed."""
    return any(
        re.search(pattern, content, re.MULTILINE | re.IGNORECASE)
        for pattern in _STATUS_COMPLETED_PATTERNS
    )


def has_substantive_implementation_summary(content: str) -> bool:
    """Return True when Implementation Summary carries a non-placeholder bullet."""
    section = _section(content, "Implementation Summary")
    if section is None:
        return False
    bullets = re.findall(r"^- [^:\n]+:[ \t]*(.+)$", section, flags=re.MULTILINE)
    if not bullets:
        bullets = re.findall(r"^- \s*(.+)$", section, flags=re.MULTILINE)
    return any(not is_placeholder(bullet) for bullet in bullets)


def has_substantive_key_proof(content: str) -> bool:
    """Return True when any proof heading carries a non-placeholder body."""
    for heading in _PROOF_HEADINGS:
        section = _section(content, heading)
        if section is not None and not is_placeholder(section):
            return True
    return False


def has_valid_human_attestation(content: str) -> bool:
    """Return True when Human Attestation carries attestor, text, and an ISO date."""
    match = re.search(
        r"^## Human Attestation\s*$([\s\S]*?)(?:^## |\n---|\Z)",
        content,
        flags=re.MULTILINE,
    )
    if not match:
        return False
    body = match.group(1)
    attestor = re.search(r"^- Attestor:\s*(.+)$", body, flags=re.MULTILINE)
    if attestor is None or is_placeholder(attestor.group(1).strip().strip("`")):
        return False
    attestation = re.search(r"^- Attestation:\s*(.+)$", body, flags=re.MULTILINE)
    if attestation is None or is_placeholder(attestation.group(1)):
        return False
    return bool(re.search(r"^- Date:\s*`?(\d{4}-\d{2}-\d{2})`?$", body, flags=re.MULTILINE))


def completion_blockers(content: str, *, requires_human: bool = True) -> list[str]:
    """Return the evidence a Completed brief is missing, empty when it is complete.

    ``requires_human`` defaults to True because ``ADR-0.0.36`` makes brief-level
    attestation universal — ``_requires_human_obpi_attestation`` returns True
    unconditionally, for every kind, lane, and sensitivity. The parameter exists
    for the one caller that still resolves it, never as a lane carve-out.
    """
    blockers: list[str] = []
    if not has_substantive_implementation_summary(content):
        blockers.append("Missing or non-substantive Implementation Summary")
    if not has_substantive_key_proof(content):
        blockers.append("Missing or non-substantive Key Proof")
    if requires_human and not has_valid_human_attestation(content):
        blockers.append("Missing human attestation content")
    return blockers


def obpi_id_from_path(rel_path: str) -> str | None:
    """Return the short OBPI id embedded in a brief path (``OBPI-0.14.0-04``)."""
    match = re.search(r"(OBPI-[\d.]+-\d+)", rel_path.replace("\\", "/"))
    return match.group(1) if match else None


def _obpi_id_matches(entry_obpi: str, obpi_id: str) -> bool:
    """Match an audit entry's OBPI id against the short id from the brief path.

    The audit ledger records full-slug ids while the path yields the short id.
    The trailing ``-`` boundary keeps ``OBPI-0.0.73-1`` from matching
    ``OBPI-0.0.73-10`` (GHI #629).
    """
    return entry_obpi == obpi_id or entry_obpi.startswith(obpi_id + "-")


def has_audit_evidence(adr_dir: Path, obpi_id: str) -> bool:
    """Return True when the ADR-local audit ledger records this OBPI's completion."""
    ledger_file = adr_dir / "logs" / "obpi-audit.jsonl"
    try:
        raw = ledger_file.read_text(encoding="utf-8")
    except OSError:
        return False
    for line in raw.splitlines():
        if not line.strip():
            continue
        try:
            entry = json.loads(line)
        except json.JSONDecodeError:
            continue
        if not isinstance(entry, dict):
            continue
        if (
            _obpi_id_matches(str(entry.get("obpi_id", "")), obpi_id)
            and str(entry.get("type", "")) in _AUDIT_TYPES
        ):
            return True
    return False


def unattested_completion_commit_message(obpi_id: str, brief_rel: str, blockers: list[str]) -> str:
    """Render the pre-commit refusal for a Completed brief with missing evidence."""
    details = "\n".join(f"  - {blocker}" for blocker in blockers)
    return (
        f"BLOCKED: {brief_rel} is staged as Completed, but its evidence is "
        f"incomplete:\n{details}\n\n"
        "WHY: the PreToolUse hook that used to catch this binds Write|Edit and keys "
        "on `tool_input.file_path`, so a `sed`, heredoc, or inline-python edit "
        "reaches the commit having passed no gate at all (GHI #844/#847). This guard "
        "reads `git diff --cached`, which every write channel lands in identically.\n\n"
        f"NEXT STEP: do not hand-edit the brief to Completed. Run the governed path, "
        f"which writes the brief, the audit ledger, and the receipt in one atomic "
        f"transaction:\n  uv run gz obpi complete {obpi_id} --attestor <name> "
        "--attestation-text '<the operator's verbatim words>'"
    )


__all__ = [
    "PLACEHOLDERS",
    "completion_blockers",
    "has_audit_evidence",
    "has_substantive_implementation_summary",
    "has_substantive_key_proof",
    "has_valid_human_attestation",
    "is_obpi_brief_path",
    "is_placeholder",
    "marks_completed",
    "obpi_id_from_path",
    "unattested_completion_commit_message",
]
