"""Single authority for the OBPI pipeline's post-Stage-2 production-code fence.

The rule lives here, not in its callers, because a second copy of a stage set is
the two-copies-one-binds shape ``ADR-0.35.0`` exists to remove — and two copies
of *this* rule would let the write locus and the commit locus drift apart
silently, which is the only way the fence can be wrong without anyone noticing.

Two loci observe it, and they are deliberately not symmetric:

``.claude/hooks/pipeline-gate.py`` (generated by
:func:`gzkit.hooks.scripts.routing._pipeline_gate_script`)
    PreToolUse, refusing the write before it lands. Fast, but bound to the
    ``Write|Edit|NotebookEdit`` matcher, so **every** ``sed`` / heredoc /
    inline-``python`` write bypasses it entirely (GHI #844, measured
    2026-08-21: 348 Bash writes, 0 gated calls, ~350 lines of production code
    authored at ``current_stage: verify``). It is an advisory fast path, never
    the guarantee.

:func:`gzkit.hooks.guards.forbid_post_authoring_src_commits`
    Pre-commit, reading ``git diff --cached``. It observes the **filesystem
    outcome**, so no tool choice evades it. This is the arm that binds.

Writing and committing are different verbs and take different rules. Authoring
production code at ``sync`` is past-Stage-2 authoring and is refused; committing
production code at ``sync`` is that stage's entire purpose (the pipeline runs
``gz git-sync --apply`` there) and is permitted. A gate that forbade its own
ceremony's required step would be un-compliable, and an un-compliable gate gets
worked around rather than obeyed.
"""

from __future__ import annotations

import json
from pathlib import Path

#: Canonical pipeline stages, in order (see :func:`gzkit.pipeline_markers.pipeline_stage_name`).
CANONICAL_STAGES: tuple[str, ...] = ("implement", "verify", "ceremony", "sync")

#: Stages in which AUTHORING production code is the declared work. Every other
#: canonical stage is post-authoring: the pipeline has left Stage 2, so a fresh
#: ``src/**`` write there is freeform implementation wearing an active marker.
AUTHORING_STAGES: frozenset[str] = frozenset({"implement"})

#: Stages from which a commit carrying production code may legitimately
#: originate. ``sync`` is included because it is the pipeline's own commit
#: stage — see the module docstring for why excluding it would be a defect.
COMMITTING_STAGES: frozenset[str] = AUTHORING_STAGES | {"sync"}

#: Path prefixes treated as production code. ``tests/**`` is deliberately absent:
#: Phase 1b ``@covers`` parity and the Phase 1c RED witness are verify-stage work
#: by design, so test writes stay open at every stage.
PRODUCTION_PREFIXES: tuple[str, ...] = ("src/",)


def is_production_path(rel_path: str) -> bool:
    """Return True when ``rel_path`` is production code the fence governs."""
    return rel_path.replace("\\", "/").startswith(PRODUCTION_PREFIXES)


def marker_stage(marker_path: Path) -> str | None:
    """Return a pipeline marker's ``current_stage``, or None when absent/unreadable.

    None is permissive by design: a marker written before this field existed
    must not start failing closed, and an unreadable marker is a separate
    defect with its own guard rather than this one's business.
    """
    try:
        payload = json.loads(marker_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    if not isinstance(payload, dict):
        return None
    stage = payload.get("current_stage")
    return str(stage) if isinstance(stage, str) and stage else None


def refuses_production_write(stage: str | None, rel_path: str) -> bool:
    """Return True when AUTHORING ``rel_path`` at ``stage`` is past-Stage-2 work.

    The write-time rule. An active marker arms the pipeline; it is never
    evidence that Stage 2 ran, so production authoring is refused once the
    marker leaves the authoring stage.
    """
    if stage is None or not is_production_path(rel_path):
        return False
    return stage not in AUTHORING_STAGES


def refuses_production_commit(stage: str | None, rel_path: str) -> bool:
    """Return True when COMMITTING ``rel_path`` at ``stage`` should be refused.

    The commit-time rule, and the one that actually binds. It diverges from
    :func:`refuses_production_write` at ``sync`` — see the module docstring.
    """
    if stage is None or not is_production_path(rel_path):
        return False
    return stage not in COMMITTING_STAGES


def post_authoring_message(obpi_id: str, stage: str, rel_path: str) -> str:
    """Render why a production WRITE is refused after Stage 2, and how to proceed."""
    return (
        f"BLOCKED: `{rel_path}` is a production write, but the pipeline "
        f"marker for {obpi_id} is at `current_stage: {stage}` - past "
        "Stage 2.\n\nWHY: an active marker is not evidence that the "
        "skill's Stage 2 ran. Stage 2 dispatches an implementer and then "
        "a two-stage spec-reviewer + quality-reviewer pass; that review "
        "is what catches hollow tests and REQ coverage bound to the wrong "
        "subject. Authoring production code at a post-authoring stage "
        "skips it while every marker-presence check still reads green."
        "\n\nNEXT STEP: if this is genuine implementation work, "
        f"re-enter Stage 2 so the review fires - `uv run gz obpi pipeline "
        f"{obpi_id}` - and let the skill dispatch it. If it is the bounded "
        "in-flight repair Stage 3 allows after a failed check, move the "
        "marker back to `implement` through the runtime so the re-entry is "
        "recorded, then repair. Do NOT hand-edit the marker to satisfy this "
        "gate (AGENTS.md Never #6).\n\n`tests/**` writes stay permitted "
        "at every stage: Phase 1b @covers parity and the Phase 1c RED "
        "witness are verify-stage work by design."
    )


def post_authoring_commit_message(obpi_id: str, stage: str, rel_paths: list[str]) -> str:
    """Render why a COMMIT carrying production code is refused after Stage 2."""
    listed = "\n".join(f"  - {p}" for p in sorted(rel_paths))
    return (
        f"BLOCKED: this commit carries production code while the pipeline "
        f"marker for {obpi_id} is at `current_stage: {stage}` - past Stage 2 "
        f"and not at the sync stage.\n\nStaged production paths:\n{listed}\n\n"
        "WHY: this gate reads the STAGED DIFF rather than a tool call, so it "
        "sees the change no matter how it was written - Edit, Write, sed, a "
        "heredoc, or an editor outside the session. The PreToolUse gate binds "
        "`Write|Edit|NotebookEdit` only and is bypassed by every other form "
        "(GHI #844). Authoring production code past Stage 2 skips the "
        "implementer dispatch and the two-stage review that catches hollow "
        "tests and REQ coverage bound to the wrong subject.\n\n"
        "NEXT STEP: if this is genuine implementation work, re-enter Stage 2 "
        f"through the runtime - `uv run gz obpi pipeline {obpi_id}` - so the "
        "dispatch is recorded, then commit. If the pipeline is ready to commit "
        "work already authored at Stage 2, advance it to `sync` through the "
        "runtime rather than editing the marker by hand (AGENTS.md Never #6).\n\n"
        "`tests/**` stays committable at every stage."
    )
