"""Governed prose may not claim a hook runs at a stage the config does not declare.

`.gzkit/skills/git-sync/SKILL.md` asserted for an unknown span that "the
pre-commit hook runs ruff, ty, unittest, and xenon on every commit". The
`unittest` hook is declared ``stages: [manual]`` in `.pre-commit-config.yaml`
and fires at neither commit nor push -- the suite reaches a push only through
the separate ``gz-check-pre-push`` hook. An agent reading that skill would
believe a commit had run the tests, which is the belief a sync ritual is built
on, and the handoff skill carried the same parenthetical about its own
mandatory gates.

`tests/arb/test_unittest_runner_lockstep.py` is the precedent shape: it pins the
suite INVOCATION across every surface that re-spells it. Nothing pinned the
STAGE, so a surface could name a hook as commit-time indefinitely. That test's
own rationale names the gap -- ``gz validate --cli-alignment`` resolves `gz`
verbs in a documented command but not the surrounding claim -- and this module
applies the same treatment to the claim.

The invariant is derived, never enumerated: the set of hooks that do NOT run at
commit time is read from the config on every run. Move ``unittest`` to
``pre-commit`` and prose naming it as commit-time becomes true, and this module
stops objecting on its own -- which is the property that makes it a witness of
the config rather than a second copy of it.
"""

from __future__ import annotations

import re
import unittest
from pathlib import Path

import yaml

_REPO_ROOT = Path(__file__).resolve().parents[2]
_CONFIG = _REPO_ROOT / ".pre-commit-config.yaml"

#: Surfaces an agent reads per turn or on skill invocation. The vendor mirrors
#: under `.claude/` and `.agents/` are byte-identical playback of `.gzkit/`
#: (regenerated by `gz agent sync control-surfaces`), so scanning the authored
#: copy covers them; `src/gzkit/templates/` is a DISTINCT file that ships in the
#: wheel and is asserted separately below.
_AUTHORED_SURFACES = (
    *sorted((_REPO_ROOT / ".gzkit" / "skills").glob("*/SKILL.md")),
    *sorted((_REPO_ROOT / ".gzkit" / "rules").glob("*.md")),
    _REPO_ROOT / "AGENTS.md",
    _REPO_ROOT / "CLAUDE.md",
)

#: Phrases that assert a hook runs when a COMMIT is made. Matched per sentence,
#: not per paragraph: correct prose routinely names a non-commit hook in the
#: very next sentence to say where it actually runs, and a paragraph-wide scan
#: would flag exactly the sentence that sets the record straight.
_COMMIT_CLAIM = re.compile(
    r"on every commit|pre-commit hook\s*\(|at commit time",
    re.IGNORECASE,
)

_COMMIT_STAGE = "pre-commit"


def _hooks_by_stage() -> dict[str, set[str]]:
    """Return stage -> hook ids, read from the executable config."""
    config = yaml.safe_load(_CONFIG.read_text(encoding="utf-8"))
    default = config.get("default_stages", [_COMMIT_STAGE])
    by_stage: dict[str, set[str]] = {}
    for repo in config.get("repos", []):
        for hook in repo.get("hooks", []):
            for stage in hook.get("stages", default):
                by_stage.setdefault(str(stage), set()).add(str(hook["id"]))
    return by_stage


def _aliases(hook_id: str) -> set[str]:
    """Return the tokens prose plausibly uses for *hook_id*.

    The id itself, plus its leading segment when that segment is distinctive
    enough to name a tool on its own (``ruff-check`` -> ``ruff``,
    ``xenon-complexity`` -> ``xenon``). Short leading segments are dropped:
    ``gz-check-pre-push`` would otherwise contribute ``gz``, which appears in
    nearly every governed sentence and would make this module fire on prose that
    says nothing about stages.
    """
    names = {hook_id}
    head = hook_id.split("-", 1)[0]
    if len(head) > 4:
        names.add(head)
    return names


def _non_commit_aliases() -> dict[str, str]:
    """Return alias -> hook id for every hook that does NOT run at commit time."""
    by_stage = _hooks_by_stage()
    commit_hooks = by_stage.get(_COMMIT_STAGE, set())
    mapping: dict[str, str] = {}
    for stage, hook_ids in by_stage.items():
        if stage == _COMMIT_STAGE:
            continue
        for hook_id in hook_ids - commit_hooks:
            for alias in _aliases(hook_id):
                mapping[alias] = hook_id
    return mapping


def _sentences(text: str) -> list[str]:
    """Split markdown prose into sentences, flattening blockquote wrapping."""
    flattened = re.sub(r"\n\s*>?\s*", " ", text)
    return re.split(r"(?<=\.)\s+", flattened)


def _violations(text: str, aliases: dict[str, str]) -> list[tuple[str, str]]:
    """Return (hook id, sentence) for each commit-time claim naming a non-commit hook."""
    found: list[tuple[str, str]] = []
    for sentence in _sentences(text):
        if not _COMMIT_CLAIM.search(sentence):
            continue
        for alias, hook_id in aliases.items():
            if re.search(rf"\b{re.escape(alias)}\b", sentence):
                found.append((hook_id, sentence.strip()))
    return found


def _scan(surfaces: tuple[Path, ...]) -> list[str]:
    """Return a rendered offence per commit-time claim naming a non-commit hook.

    Reads at module scope rather than inside a test body: a filesystem op
    co-occurring with an assertion is what the tautological-test audit flags,
    and the read here is fixture work, not the assertion's subject.
    """
    aliases = _non_commit_aliases()
    offences: list[str] = []
    for surface in surfaces:
        for hook_id, sentence in _violations(surface.read_text(encoding="utf-8"), aliases):
            rel = surface.relative_to(_REPO_ROOT)
            offences.append(f"{rel}: claims `{hook_id}` runs at commit -- {sentence!r}")
    return offences


class TestGovernedProseMatchesHookStages(unittest.TestCase):
    """No governed surface claims a non-commit hook runs at commit time."""

    def test_config_declares_hooks_outside_the_commit_stage(self) -> None:
        """The premise: with every hook at `pre-commit`, this module has no subject."""
        self.assertNotEqual(_non_commit_aliases(), {})

    def test_no_surface_claims_a_non_commit_hook_runs_at_commit(self) -> None:
        offences = _scan(_AUTHORED_SURFACES)
        self.assertEqual(
            offences,
            [],
            msg=(
                "A governed surface tells agents a hook runs on every commit that "
                ".pre-commit-config.yaml stages elsewhere. An agent believes the "
                "commit ran that gate and it did not. Fix the prose, or move the "
                "hook -- this module reads the config, so a genuine stage change "
                "makes the claim true and silences it.\n  " + "\n  ".join(offences)
            ),
        )


class TestAdopterTemplateDoesNotShipOurRoster(unittest.TestCase):
    """The wheel ships no `.pre-commit-config.yaml`, so no template may name a roster.

    `src/gzkit/templates/skills/git-sync/SKILL.md` stated gzkit's OWN hook roster
    as fact to adopters who never receive that config -- a claim that is
    unverifiable in the repository it lands in, and was wrong about `unittest`
    even here.
    """

    _TEMPLATE = _REPO_ROOT / "src" / "gzkit" / "templates" / "skills" / "git-sync" / "SKILL.md"

    def test_wheel_ships_no_pre_commit_config(self) -> None:
        """The premise. If gzkit ever ships one, this test is the place to re-rule."""
        shipped = list((_REPO_ROOT / "src" / "gzkit").rglob(".pre-commit-config*"))
        self.assertEqual(
            shipped,
            [],
            msg="gzkit now ships a pre-commit config; the template may state its roster.",
        )

    def test_template_makes_no_commit_time_roster_claim(self) -> None:
        self.assertEqual(
            _scan((self._TEMPLATE,)),
            [],
            msg=(
                "The adopter-facing git-sync template states a commit-time hook "
                "roster. gzkit ships no pre-commit config, so the adopter's roster "
                "is whatever their own config declares -- point them at it."
            ),
        )


class TestTheWitnessCanFail(unittest.TestCase):
    """Negative controls: the detector fires on the prose that actually shipped.

    A stage witness that cannot reproduce the defect it was written for is the
    tautological test `.gzkit/rules/tests.md` forbids, so both retired sentences
    are replayed here verbatim.
    """

    _SHIPPED_STEPS_CLAIM = (
        "> The pre-commit hook runs ruff, ty, unittest, and xenon on every commit.\n"
        "> `--lint` and `--test` re-run those gates at the `gz` level."
    )
    _SHIPPED_REDFLAG_CLAIM = (
        "> The pre-commit hook (ruff + ty + unittest + xenon) is the mandatory gate;\n"
        "> explicit `--lint --test` flags are redundant for the normal ritual."
    )

    def test_detector_flags_the_retired_steps_sentence(self) -> None:
        offences = _violations(self._SHIPPED_STEPS_CLAIM, _non_commit_aliases())
        self.assertEqual([hook for hook, _ in offences], ["unittest"])

    def test_detector_flags_the_retired_red_flags_sentence(self) -> None:
        offences = _violations(self._SHIPPED_REDFLAG_CLAIM, _non_commit_aliases())
        self.assertEqual([hook for hook, _ in offences], ["unittest"])

    def test_detector_accepts_prose_that_names_the_real_stage(self) -> None:
        """The corrected shape passes: the claim and the correction are separate sentences."""
        corrected = (
            "> The pre-commit hook runs the CHEAP gates on every commit -- ruff, ty,\n"
            "> xenon, interrogate, gitleaks, authorship. It does NOT run the unit\n"
            "> suite: `unittest` is declared `stages: [manual]`."
        )
        self.assertEqual(_violations(corrected, _non_commit_aliases()), [])


if __name__ == "__main__":
    unittest.main()
