"""The pre-push gate must be scaffolded, activated, and verified for adopters (GHI #715).

ADR-0.0.68's intent is a gate that fires between sessions. Three gaps let a
project satisfy every green surface while enforcing nothing:

1. ``gz init`` never wrote ``.pre-commit-config.yaml``, so an adopter's very
   first ``gz check`` failed closed on a file gzkit told them to hand-author.
2. ``gz init`` never ran ``pre-commit install``, so even a repo carrying the
   config ran every commit and push unenforced.
3. The delivery arm was opt-in and reachable only from ``gz git-sync``, so an
   adopter who never synced got no signal — and a ``core.hooksPath`` set after
   installation silently re-disabled everything.

These tests pin the producer (init) to the consumer (the delivery audit) so a
change to either surface that breaks the pairing fails here.
"""

import os
import subprocess
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from gzkit.governance.trust_audits.session_green_gate import audit_session_green_gate

_PRE_COMMIT_SHIM = (
    "#!/usr/bin/env bash\n# File generated by pre-commit: https://pre-commit.com\n"
    "exec pre-commit hook-impl --hook-type=pre-push\n"
)


def _worktree(root: Path) -> None:
    """Create a bare git worktree shape: ``.git/`` with an empty hooks dir."""
    (root / ".git" / "hooks").mkdir(parents=True, exist_ok=True)


def _declared_worktree(root: Path) -> None:
    """A worktree that declares the gate but has not installed it.

    The activation step presupposes a config — with none there is nothing to
    install — so every install-path test starts from the declared state.
    """
    from gzkit.commands.init_cmd import _scaffold_pre_commit_config

    _worktree(root)
    _scaffold_pre_commit_config(root)


class ScaffoldPreCommitConfig(unittest.TestCase):
    """``gz init`` must deliver the config the session-green-gate demands."""

    def test_scaffolded_config_satisfies_the_declaration_audit(self) -> None:
        """The scaffolder and the auditor must agree — that is the whole contract.

        Asserting against ``audit_session_green_gate`` rather than the YAML text
        means a drift in either surface fails here, which is the coupling that
        was missing when init shipped no config at all.
        """
        from gzkit.commands.init_cmd import _scaffold_pre_commit_config

        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            self.assertTrue(audit_session_green_gate(root), "precondition: no config yet")
            _scaffold_pre_commit_config(root)
            self.assertEqual(
                audit_session_green_gate(root),
                [],
                "scaffolded .pre-commit-config.yaml must declare the pre-push gz check gate",
            )

    def test_existing_config_is_never_overwritten(self) -> None:
        from gzkit.commands.init_cmd import _scaffold_pre_commit_config

        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            config = root / ".pre-commit-config.yaml"
            config.write_text("# operator's own config\nrepos: []\n", encoding="utf-8")
            _scaffold_pre_commit_config(root)
            self.assertIn(
                "operator's own config",
                config.read_text(encoding="utf-8"),
                "an existing config is operator canon and must survive init",
            )

    def test_dry_run_writes_nothing(self) -> None:
        from gzkit.commands.init_cmd import _scaffold_pre_commit_config

        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            _scaffold_pre_commit_config(root, dry_run=True)
            self.assertFalse((root / ".pre-commit-config.yaml").exists())


class InstallPreCommitHooks(unittest.TestCase):
    """``gz init`` must activate the gate, not merely declare it."""

    def _fake_installer(self, root: Path):
        """Return a ``subprocess.run`` double that behaves like ``pre-commit install``."""

        def run(cmd, **kwargs):  # noqa: ANN001, ANN003
            if "install" in cmd:
                (root / ".git" / "hooks" / "pre-push").write_text(
                    _PRE_COMMIT_SHIM, encoding="utf-8"
                )
                return subprocess.CompletedProcess(cmd, 0, "", "")
            return subprocess.CompletedProcess(cmd, 1, "", "unexpected")

        return run

    def test_install_leaves_the_gate_delivered(self) -> None:
        """After init, the delivery arm must pass — the producer/consumer pairing."""
        from gzkit.commands.init_cmd import _install_pre_commit_hooks

        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            _declared_worktree(root)
            self.assertTrue(
                audit_session_green_gate(root, check_delivery=True),
                "precondition: declared but not delivered",
            )
            with patch("subprocess.run", side_effect=self._fake_installer(root)):
                _install_pre_commit_hooks(root)
            self.assertEqual(
                audit_session_green_gate(root, check_delivery=True),
                [],
                "gz init must leave the declared gate installed",
            )

    def test_hooks_path_set_reports_instead_of_invoking_a_refusal(self) -> None:
        """pre-commit refuses when core.hooksPath is set — do not spend the subprocess.

        This is the exact condition that ran unenforced in the gzkit repo for six
        weeks: the redirect pointed at git's own default, so it was invisible,
        and every install attempt refused.
        """
        from gzkit.commands.init_cmd import _install_pre_commit_hooks

        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            _declared_worktree(root)
            (root / ".git" / "config").write_text(
                "[core]\n\thooksPath = .git/hooks\n", encoding="utf-8"
            )
            with patch("subprocess.run") as spawned:
                status = _install_pre_commit_hooks(root)
            spawned.assert_not_called()
            self.assertIsNotNone(status, "the operator must be told activation was blocked")
            self.assertIn(
                "core.hooksPath",
                str(status),
                "recovery prose must name the blocking setting (guardrail-feedback-prose)",
            )

    def test_non_git_tree_is_skipped(self) -> None:
        from gzkit.commands.init_cmd import _install_pre_commit_hooks

        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            with patch("subprocess.run") as spawned:
                self.assertIsNone(_install_pre_commit_hooks(root))
            spawned.assert_not_called()

    def test_installer_failure_is_reported_not_raised(self) -> None:
        """A missing pre-commit must not abort init — the audit is the fail-closed arm."""
        from gzkit.commands.init_cmd import _install_pre_commit_hooks

        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            _declared_worktree(root)
            with patch("subprocess.run", side_effect=FileNotFoundError("pre-commit")):
                status = _install_pre_commit_hooks(root)
            self.assertIsNotNone(status, "a failed activation must still be reported")


class DeliveryArmDefaultScope(unittest.TestCase):
    """Gap 2 + gap 3: the delivery arm must bind in ``gz check``, except under CI."""

    def _undelivered(self, root: Path) -> None:
        _declared_worktree(root)

    def _run_scope(self, root: Path) -> list:
        from gzkit.commands.validate_cmd import VALIDATOR_REGISTRY

        entry = next(e for e in VALIDATOR_REGISTRY if e.stem == "session_green_gate")
        return entry.run(root, None)

    def test_undelivered_gate_fails_the_validator_outside_ci(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            self._undelivered(root)
            with patch.dict(os.environ, {}, clear=False):
                os.environ.pop("CI", None)
                errors = self._run_scope(root)
        self.assertTrue(
            errors,
            "an adopter who never runs git-sync must still learn the gate is not installed",
        )

    def test_ci_checkout_is_carved_out(self) -> None:
        """CI legitimately has no hooks — CI *is* the gate there and does not push."""
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            self._undelivered(root)
            with patch.dict(os.environ, {"CI": "true"}):
                errors = self._run_scope(root)
        self.assertEqual(errors, [], "the delivery arm must not fail every CI run")

    def test_declaration_arm_still_binds_under_ci(self) -> None:
        """The CI carve-out suppresses delivery only — never the declaration."""
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            with patch.dict(os.environ, {"CI": "true"}):
                errors = self._run_scope(root)
        self.assertTrue(errors, "a missing declaration must fail closed even under CI")


if __name__ == "__main__":
    unittest.main()
